# Generated by Django 3.2.9 on 2022-03-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
