# Generated by Django 3.2.9 on 2022-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220326_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default_user.png', upload_to='profiles', verbose_name='Фото'),
        ),
    ]
