# Generated by Django 3.2.9 on 2022-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
